application: anemia-dd-helper
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /.*
  script: anemia_diff.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$ 
- ^node_modules$
- ^bower_components$
